## Numpy Slicing Stacking and Indexing with boolean arrays

In [1]:
import numpy as np

In [2]:
# numpy array support same kind of slicing method like in python array

In [3]:
a = np.array([6,7,8])

In [4]:
a[0:2]

array([6, 7])

In [5]:
a[2]

8

In [6]:
a[-1]

8

In [7]:
a = np.array([[6,7,8],[1,2,3],[9,8,7]])

In [8]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 8, 7]])

In [9]:
a.ndim

2

In [10]:
a.shape

(3, 3)

In [11]:
a[1,2]

3

In [12]:
a[0:2,2]

array([8, 3])

In [13]:
a[-1]

array([9, 8, 7])

In [14]:
a[-1,-1]

7

In [15]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [8, 7]])


### Iterate Through an array

In [16]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 8, 7]])

In [17]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 8 7]


In [18]:
for cell in a.flat:
    print(cell)
# print individual cell value    

6
7
8
1
2
3
9
8
7



### Stacking Through an array

In [19]:
a = np.arange(6).reshape(3,2)

In [20]:
b = np.arange(6,12).reshape(3,2)

In [21]:
a,b

(array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]]))

In [22]:
np.vstack((a,b)) # to stack two array vertically 

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [23]:
# like a and b are twwo boxes and they lie in stack position  

In [24]:
np.hstack((b,a)) # stack horizontally -- its a type of tuple

array([[ 6,  7,  0,  1],
       [ 8,  9,  2,  3],
       [10, 11,  4,  5]])

### Split array

In [25]:
a = np.arange(30).reshape(2,15)

In [26]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [27]:
result = np.hsplit(a,3) #split horizontally

In [28]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [29]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [30]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [31]:
type(result)

list

In [32]:
result = np.vsplit(a,2) #split vertically

In [33]:
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [34]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [35]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [36]:
result[2]

IndexError: list index out of range

### Indexing with boolean array

In [ ]:
a = np.arange(12).reshape(3,4)

In [ ]:
a

In [ ]:
b = a > 4 
# create an np array with type boolean which has the value greater than 4

In [ ]:
b

In [ ]:
a[b] 
# when b is true it return those value

In [ ]:
a[b] =-1
# all the elements which is greater than 4 is assign the value of -1

In [ ]:
a

## Python Numpy Read Write Text Files

In [ ]:
x = np.arange(10).reshape(2,5)

In [ ]:
x

In [ ]:
np.savetxt("test.txt",x) #to save the array of file

In [ ]:
y = np.loadtxt("test.txt") # to read the test.txt file

In [ ]:
y

### iteraate using nditer

In [37]:
a = np.arange(12).reshape(3,4)

In [38]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
for cell in np.nditer(a,order="c"):
    print(cell)
    # C order means row by row

0
1
2
3
4
5
6
7
8
9
10
11


In [44]:
for cell in np.nditer(a,order="F"):
    print(cell)
    # C order means column by column

0
4
8
1
5
9
2
6
10
3
7
11


In [46]:
for cell in np.nditer(a,order="F",flags=["external_loop"]):
    print(cell)
    # C order means row by row

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [47]:
for x in np.nditer(a,op_flags=["readwrite"]):
    x[...] = x*x
    
    #to make the element of square

In [48]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [49]:
b =np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [50]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
