# Numpy Tutorial

In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3])

In [3]:
arr


array([1, 2, 3])

In [4]:
type(arr)

numpy.ndarray

### Type() 
- built in python function to shows the type of objects

In [5]:
arr[2]+arr[1]


5

In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [7]:
arr = np.arange(1000
               )

In [9]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

to add two arrays
it add two array like matrices


In [14]:
arr1 = np.array([[1,2],[3,4]])


In [15]:
arr2 = np.array([[5,6],[7,8]])


In [16]:
result = arr1 + arr2


In [17]:
result

array([[ 6,  8],
       [10, 12]])

numpy is fast and efficient


ndim --> to shows the dimension of array

In [19]:
result.ndim


2

itemsize --> shows the size of array
size --> shows the element no of array 

In [20]:
arr1.itemsize


4

In [21]:
arr1.size

4

dtype --> display  the data size of array

shape -- > display the width and height of array (rows , column)

In [22]:
arr1.shape

(2, 2)

## Numpy Function

In [23]:
# np.zeros((3,2)) ---> create an array with placeholder number

In [24]:
a.npzeros((3,2))

NameError: name 'a' is not defined

In [25]:
a = np.zeros((3,2))

In [26]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
# we also do the same thing with ones

In [28]:
a.npones(3,4)

AttributeError: 'numpy.ndarray' object has no attribute 'npones'

In [29]:
a = np.ones((3,4))

In [30]:
a


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
# np.arange(no of elements) --> to create an array of dummy data with a specific range

In [32]:
a = np.arange(10)

In [33]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(1,5)

array([1, 2, 3, 4])

In [40]:
np.arange(1,8,2) # (start,end -1, elements skip)

array([1, 3, 5, 7])

In [43]:
# np.linspace(start,stop,no of elements) 
# the gap between the element is equal

In [45]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [46]:
a = np.array([[5,7,9],[1,4,5]])

In [48]:
a.shape

(2, 3)

In [ ]:
# reshape will change the shape/ dimension of array

In [49]:
a.reshape(3,2)

array([[5, 7],
       [9, 1],
       [4, 5]])

In [51]:
# a.reshape(6,1)

array([[5],
       [7],
       [9],
       [1],
       [4],
       [5]])

In [ ]:
# np.ravel() --> it will flaten your array to 1 row

In [53]:
a.ravel()

array([5, 7, 9, 1, 4, 5])

In [54]:
a.min()

1

In [55]:
a.max()

9

In [56]:
# a.min() --> for minimum value
# a.max() --> for maximum number

In [57]:
a

array([[5, 7, 9],
       [1, 4, 5]])

In [58]:
a.sum()

31

In [59]:
# a.sum() --> to sum all the elements of an array

### Axis 
Axis0 --> vertical axis
Axis1 --> horizontal axis

In [60]:
a.sum(axis=0)

array([ 6, 11, 14])

In [61]:
a.sum(axis=1)

array([21, 10])

In [62]:
# np.sqrt(a) --> to compute each of the elements of sq-root 

In [63]:
np.sqrt(a)

array([[2.23606798, 2.64575131, 3.        ],
       [1.        , 2.        , 2.23606798]])

In [64]:
# np.std(a) --> to find the standard deviation of all the elements

### Mathmatical operation

In [65]:
a = np.array([[1,5,7],[8,9,0]])

In [66]:
b = np.array([[3,8,9],[3,9,0]])

In [67]:
a

array([[1, 5, 7],
       [8, 9, 0]])

In [68]:
b

array([[3, 8, 9],
       [3, 9, 0]])

In [69]:
a+b # for additon the value of matrix

array([[ 4, 13, 16],
       [11, 18,  0]])

In [70]:
a-b # for subtract the value of matrix

array([[-2, -3, -2],
       [ 5,  0,  0]])

In [71]:
a*b # for Multiply the value of matrix

array([[ 3, 40, 63],
       [24, 81,  0]])

In [72]:

a/b # for Division the value of matrix

C:\Users\AK TRADER\AppData\Local\Temp\ipykernel_10100\935209152.py:1: RuntimeWarning: invalid value encountered in true_divide
  a/b # for Division the value of matrix


array([[0.33333333, 0.625     , 0.77777778],
       [2.66666667, 1.        ,        nan]])

In [74]:
b.dot(a) # for Matrix product

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [75]:
a = np.array([[1,3],[5,4]])

In [76]:
b = np.array([[2,3],[6,4]])

In [78]:
a.dot(b) # For Matrix Product

array([[20, 15],
       [34, 31]])